# Generated by Django 2.0 on 2020-10-09 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommentInfo_India',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, max_length=20, null=True, verbose_name='keywords')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='title')),
                ('content', models.CharField(blank=True, max_length=5000, null=True, verbose_name='content')),
                ('url', models.CharField(blank=True, max_length=300, null=True, verbose_name='URL')),
                ('time', models.DateField(blank=True, null=True, verbose_name='date')),
                ('mediatype', models.CharField(blank=True, max_length=10, null=True, verbose_name='media source')),
                ('attribute', models.CharField(blank=True, max_length=10, null=True, verbose_name='ttributes')),
                ('heat', models.IntegerField(blank=True, null=True, verbose_name='heat')),
            ],
            options={
                'verbose_name': 'Details',
                'verbose_name_plural': 'Details',
            },
        ),
        migrations.CreateModel(
            name='KeyWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=20, verbose_name='keyword')),
                ('username', models.CharField(max_length=20, verbose_name='operating_name')),
                ('status', models.CharField(max_length=20, verbose_name='crawlign_status')),
            ],
            options={
                'verbose_name': '舆情关键词',
                'verbose_name_plural': '舆情关键词',
            },
        ),
    ]
