# Generated by Django 2.1 on 2020-11-19 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word_Accuracy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='日期')),
                ('word_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='敏感词ID')),
                ('content', models.CharField(blank=True, max_length=10000, null=True, verbose_name='敏感词内容')),
                ('countrys', models.CharField(blank=True, max_length=20, null=True, verbose_name='国家码')),
                ('level', models.CharField(blank=True, max_length=20, null=True, verbose_name='等级')),
                ('remark', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
                ('stype', models.CharField(blank=True, max_length=20, null=True, verbose_name='词类型')),
                ('sensitive_type', models.CharField(blank=True, max_length=20, null=True, verbose_name='违规类型')),
                ('status', models.CharField(blank=True, max_length=20, null=True, verbose_name='状态')),
                ('source', models.CharField(blank=True, max_length=20, null=True, verbose_name='质检来源')),
                ('cnt7', models.IntegerField(blank=True, max_length=11, null=True, verbose_name='过去7天质检量')),
                ('accuracy7', models.FloatField(blank=True, null=True, verbose_name='7天准确率')),
                ('cnt30', models.IntegerField(blank=True, max_length=11, null=True, verbose_name='过去30天质检量')),
                ('accuracy30', models.FloatField(blank=True, null=True, verbose_name='30天准确率')),
            ],
            options={
                'verbose_name_plural': 'accuracy',
                'verbose_name': 'accuracy',
            },
        ),
    ]
